### ISSUE TITLE
What's the real mean of expression data/level

### ISSUE THREAD

**Issue by Chenleinice** [drostlab/myTAI#10]
Dear Dr. Hajk-Georg Drost
Great work on the integration of gene evolution and transcriptome. However, I‘m confused about what's expression data, TPM, FPKM, or just read counts? 
Many thanks for your help!
Yours sincerely,
Lei Chen

**Comment by HajkD** [comment]
Dear Lei Chen,

Thank you for your question and glad to hear you find `myTAI` useful.

Expression data assumes TPMs normalized across developmental stages so that 'absolute TPM' values can be compared between developmental stages (/replicates).

I hope this helps!

Cheers,
Hajk

**Comment by HajkD** [comment]
P.s. If helper packages such as `edgeR` or `DESeq2` are used for differential gene expression analysis, then `ExpressionSet` refers to the count or normalised count matrices expected by `edgeR` or `DESeq2`.
