### ISSUE TITLE
Citations in the DESCRIPTION file

### ISSUE THREAD

**Issue by LotharukpongJS** [drostlab/myTAI#14]
Hi Hajk,

From the conda recipe file of #13 , I noticed that the citations in the package summary can be improved, i.e.

```
  summary: Investigate the evolution of biological processes by capturing evolutionary signatures in transcriptomes (Drost et al. (2017) <doi:10.1093/bioinformatics/btx835>). The aim of this tool is to provide a transcriptome analysis environment to quantify the average evolutionary age of genes contributing to a transcriptome of interest (Drost et al. (2016) <doi:10.1101/051565>).
```

This summary was most likely generated automatically from this line in the DESCRIPTION file.

https://github.com/drostlab/myTAI/blob/8e92367021e07a3ea7759bf44f69636a7ea39b27/DESCRIPTION#L15

Perhaps the reference to Drost et al (2017) can be changed to Drost et al (2018). Furthermore, I am unsure whether citation for the BioRxiv article (Drost et al. (2016) <doi:10.1101/051565>) is needed.

Let me know what you think.

Best,
Sodai

**Comment by HajkD** [comment]
Hi Sodai,

Sounds great to me. Feel free to send an PR 👍 

Many thanks,
Hajk
