### ISSUE TITLE
p-value in `PlotSignature()`as subtitle

### ISSUE THREAD

**Issue by LotharukpongJS** [drostlab/myTAI#16]
**Is your feature request related to a problem? Please describe.**
The p values (e.g. p_flt) from the `PlotSignature()` function are added via `ggplot2::annotate()` and don't always fit the screen when making a small figure.

```r
data(PhyloExpressionSetExample)
p <- PlotSignature(ExpressionSet = PhyloExpressionSetExample, permutations = 100)
p
```
<img width="365" alt="Screenshot 2023-07-06 at 13 54 43" src="https://github.com/drostlab/myTAI/assets/80110649/13d71011-f22a-4f64-9a74-8eac4a9f68f0">

**Describe the solution you'd like**
Perhaps the p-value can be passed as the subtitle for the plot. This will remove the issue of the text being cut off when making small figures. Here is an example implementation (without the preexisting p-value label).

```r
p + ggplot2::labs(subtitle = ggplot2::ggplot_build(p)$data[[3]][["label"]])
# ggplot2::ggplot_build(p)$data[[3]][["label"]] extracts the annotation from the ggplot2 object.
```
<img width="359" alt="Screenshot 2023-07-06 at 15 09 38" src="https://github.com/drostlab/myTAI/assets/80110649/b84986b6-ae75-4bb8-8266-f260fcd19f4e">

However, this removes the flexibility users might have when they want to customise the subtitle themselves.
On the other hand, it also makes sense for the p-value to be presented in the subtitle. When the size is too big, the size of the subtitle can be changed.

```r
p + ggplot2::labs(subtitle = ggplot2::ggplot_build(p)$data[[3]][["label"]]) + 
  ggplot2::theme(plot.subtitle = ggplot2::element_text(size=18, face="italic"))
```

<img width="355" alt="Screenshot 2023-07-06 at 15 24 55" src="https://github.com/drostlab/myTAI/assets/80110649/b0a041fa-c42c-4819-85fe-c519401f1dcf">

Whereas it is non-trivial to edit (or remove in the case above) annotations (`ggplot2::annotate("text", ...)`) _post-facto_.
https://stackoverflow.com/questions/20083700/how-to-have-annotated-text-style-to-inherit-from-theme-set-options

(Let me know if otherwise)

**Describe alternatives you've considered**
Move the coordinate of the annotation. However, this can also lead to a similar issue (1. the label may not fit the plot & 2. it is unclear [to me] how annotations can be modified _post-facto)._

**Additional context**
Lines implicated in https://github.com/drostlab/myTAI/blob/master/R/PlotSignature.R

https://github.com/drostlab/myTAI/blob/e8c12b12de4b6b5ce07aaa046ed199c6277e3e41/R/PlotSignature.R#L295-L302

https://github.com/drostlab/myTAI/blob/e8c12b12de4b6b5ce07aaa046ed199c6277e3e41/R/PlotSignature.R#L310-L317

https://github.com/drostlab/myTAI/blob/e8c12b12de4b6b5ce07aaa046ed199c6277e3e41/R/PlotSignature.R#L338-L345

etc.

**Comment by HajkD** [comment]
Hi @LotharukpongJS 

Sounds good to me to place the p-value into the legend title.

Feel free to send me a PR and I will merge it in!

With many thanks and very best wishes,
Hajk
