### ISSUE TITLE
using an API key

### ISSUE THREAD

**Issue by erinhunter4** [drostlab/myTAI#7]
Is there a way to add an API key to searches with myTAI? I am searching a large number of entries and not having an API key associated with my search is killing my script.

**Comment by HajkD** [comment]
Could you please provide a concrete example, so that I can see what application you have in mind? 
Are you referring to the `myTAI::taxonomy()` function?

**Comment by erinhunter4** [comment]
Yeah. I realised through reading the taxize documentation that I needed to have the API key in my R environment. Not sure if that was written somewhere and I missed it but that has solved the problem.
