### ISSUE TITLE
TAI for transcriptomes in different conditions

### ISSUE THREAD

**Issue by weikai-320722** [drostlab/myTAI#8]
Hi, 

I know TAI is used to estimate transcriptome age in different stages of development. If it also can be used to estimate age in different conditions, for example in drought, cold. I sequenced 16 samples (8 control sample and 8 drought sample), I calculated TAI in 16 samples, and got perfect results. So, I just want to ask you if TAI is also suitable to evaluate age of different transcriptomes in different conditions.

Thanks,

Kai

**Comment by HajkD** [comment]
Hi Kai,

Thank you for this great question!

Yes, you can absolutely use TAI for any biological process or stress condition to characterise the evolutionary age of the underlying transcriptome. In fact, in our publication https://academic.oup.com/bioinformatics/article/34/9/1589/4772684 we encourage the use of TAI for any biological process and beyond developmental genetics questions. 

I hope this helps and I am happy to hear that `myTAI` allowed you to obtain exciting results for your research!

Cheers,
Hajk

**Comment by weikai-320722** [comment]
Thanks Hajk !
